language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-image -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-image yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-370574376533"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"
